services:
  inventory-shop-web-app-pet:
    image: inventory-shop-web-app-pet
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    container_name: inventory-shop-web-app-pet
    depends_on:
      - db
      - cache
  db:
    image: postgres:latest
    container_name: inventory-shop-db-postgresql
    ports:
      - "9088:5432"
    environment:
      - POSTGRES_USER=inv_shop_user
      - POSTGRES_PASSWORD=5678
      - POSTGRES_DB=inventory_shop_db
    volumes:
      - db_data:/var/lib/postgresql
  cache:
    image: redis:latest
    container_name: inventory-shop-cache-redis
    ports:
      - "9089:6379"
    volumes:
      - cache_data:/data
    command: redis-server --appendonly yes
volumes:
  db_data:
  cache_data: