// <auto-generated />
using System;
using System.Collections.Generic;
using InventoryShop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryShop.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryShopDbContext))]
    partial class InventoryShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryShop.Domain.Entities.ItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StatsModifiers", "InventoryShop.Domain.Entities.ItemEntity.StatsModifiers#Stats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Agility")
                                .HasColumnType("integer");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("integer");

                            b1.Property<int>("Strength")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Wallet", "InventoryShop.Domain.Entities.PlayerEntity.Wallet#Wallet", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("GoldAmount")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("PasswordHashed")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.ShopOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.ShopSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "InventoryShop.Domain.Entities.ShopSlotEntity.Price#Wallet", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("GoldAmount")
                                .HasColumnType("bigint");
                        });

                    b.HasKey("Id");

                    b.ToTable("ShopSlots");
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.PlayerEntity", b =>
                {
                    b.OwnsOne("InventoryShop.Domain.ValueObjects.LevelProgress", "LevelProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Experience")
                                .HasColumnType("bigint");

                            b1.Property<long>("Level")
                                .HasColumnType("bigint");

                            b1.HasKey("PlayerEntityId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerEntityId");
                        });

                    b.Navigation("LevelProgress")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.ShopOrderEntity", b =>
                {
                    b.OwnsOne("InventoryShop.Domain.ValueObjects.OrderData", "OrderData", b1 =>
                        {
                            b1.Property<Guid>("ShopOrderEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("RequiredLevel")
                                .HasColumnType("bigint");

                            b1.HasKey("ShopOrderEntityId");

                            b1.ToTable("ShopOrders");

                            b1.WithOwner()
                                .HasForeignKey("ShopOrderEntityId");

                            b1.OwnsOne("InventoryShop.Domain.ValueObjects.ItemSnapshot", "ItemSnapshot", b2 =>
                                {
                                    b2.Property<Guid>("OrderDataShopOrderEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid?>("CreatorId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Description")
                                        .HasColumnType("text");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("OrderDataShopOrderEntityId");

                                    b2.ToTable("ShopOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderDataShopOrderEntityId");

                                    b2.OwnsOne("InventoryShop.Domain.ValueObjects.Stats", "StatsModifiers", b3 =>
                                        {
                                            b3.Property<Guid>("ItemSnapshotOrderDataShopOrderEntityId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("Agility")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Intelligence")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Strength")
                                                .HasColumnType("integer");

                                            b3.HasKey("ItemSnapshotOrderDataShopOrderEntityId");

                                            b3.ToTable("ShopOrders");

                                            b3.WithOwner()
                                                .HasForeignKey("ItemSnapshotOrderDataShopOrderEntityId");
                                        });

                                    b2.Navigation("StatsModifiers")
                                        .IsRequired();
                                });

                            b1.OwnsOne("InventoryShop.Domain.ValueObjects.Wallet", "Price", b2 =>
                                {
                                    b2.Property<Guid>("OrderDataShopOrderEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<long>("GoldAmount")
                                        .HasColumnType("bigint");

                                    b2.HasKey("OrderDataShopOrderEntityId");

                                    b2.ToTable("ShopOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderDataShopOrderEntityId");
                                });

                            b1.Navigation("ItemSnapshot")
                                .IsRequired();

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("OrderData")
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryShop.Domain.Entities.ShopSlotEntity", b =>
                {
                    b.OwnsOne("InventoryShop.Domain.ValueObjects.LevelProgress", "RequiredLevel", b1 =>
                        {
                            b1.Property<Guid>("ShopSlotEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("Experience")
                                .HasColumnType("bigint");

                            b1.Property<long>("Level")
                                .HasColumnType("bigint");

                            b1.HasKey("ShopSlotEntityId");

                            b1.ToTable("ShopSlots");

                            b1.WithOwner()
                                .HasForeignKey("ShopSlotEntityId");
                        });

                    b.Navigation("RequiredLevel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
